---
- name: setup and enable supervisor
  import_tasks: root.yml
  become: true
  when: wrt_use_supervisor |bool
  tags: wrt_supervisor_all

- name: run postponed handlers now
  meta: flush_handlers
...
